### PR TITLE
Try using DocumenterVitepress.jl

### PR DESCRIPTION
**Pull request by avik-pal**
- [x] https://github.com/LuxDL/DocumenterVitepress.jl/issues/48
- [x] https://github.com/LuxDL/DocumenterVitepress.jl/issues/69
- [x] ~Buildkite environment not correctly detected (maybe documentervitepress problem?)~ forcing the deployment by setting clean md folder
- [x] Change github deployment settings
- [x] https://github.com/LuxDL/DocumenterVitepress.jl/pull/82 is needed

### CODE REVIEW

**Comment by avik-pal** [comment]
https://buildkite.com/julialang/lux-dot-jl/builds/1144#018e247a-e669-4be8-98d1-7b31474f1aa9/2489-4395 deploy decision inside Vitepress fails because it can't detect the documenter key, but `deploydocs` decision passes and it can detect the key, which is very strange.

@asinghvi17 do you know if this is some problem in the lux buildkite config or the deployment in markdownvitepress?

**Comment by avik-pal** [comment]
yes all the "SECRET_XYZ" keys get converted to "XYZ" after decryption and are added to the Environemnt.

**Comment by avik-pal** [comment]
@asinghvi17 am I doing something wrong here? https://lux.csail.mit.edu/previews/PR496/ doesn't seem to render correctly

**Comment by avik-pal** [comment]
https://github.com/LuxDL/Lux.jl/blob/5777654a864c294a71faaceac1f57c46be53ea6a/docs/make.jl#L84-L86 I have added the domain and stuff

**Comment by avik-pal** [comment]
the path here is https://github.com/LuxDL/Lux.jl/blob/07080e4f2a74ed9f5036b17bc0ebf9a07d76b542/previews/PR496/introduction/index.html#L9 definitely incorrect

**Comment by asinghvi17** [comment]
Huh, yeah it definitely looks like a base path issue

**Comment by avik-pal** [comment]
https://lux.csail.mit.edu/previews/PR496/ beautiful :tada:

**Pull request merged**
